### ISSUE TITLE
Brier score greater than 1

### ISSUE THREAD

**Issue by gaomrx** [biolab/orange#29]
Obtained a Brier score greater than 1 when running 5 folds cross validation using Naive Bayes. Wikipedia claims the range of Brier scores to be between 0 and 1. Can someone verify if this was an error? Thanks.

![1](https://cloud.githubusercontent.com/assets/6380557/8342879/abcd057e-1a9d-11e5-9b42-d37169bc0000.PNG)

**Comment by janezd** [comment]
Which data do you have? With how many classes? Judging by your low accuracy (< 0.5), you probably have multiple classes. Brier score is below 1 if it is normalized. Orange uses unnormalized Brier score.

**Comment by gaomrx** [comment]
That makes sens, seeing it says \sum_x(t(x) - p(x))^2 on the documentation page. 

I have just 2 classes but over 10K features. FYI, 5 folds cross validation using Naive Bayes or SVM with the same data on Orange Canvas is either too slow or not possible due to memory issue.

**Comment by janezd** [comment]
For Bayes, try discretizing the continuous features into, say, four bins. It is probably slow because it needs to approximate density distributions, and it uses LOESS for this.

For SVM, certain steps of data preprocessing might be slow by I forgot the details.

You can also try Orange 3 (beta!). It should use much less memory and learning should (in general) be faster.

**Comment by gaomrx** [comment]
Thanks, I will probably try writing my own classifier and compare the results.
